name: Generate Daily Article

on:
  schedule:
    # 毎日日本時間9:00に実行（UTC 0:00）
    - cron: '0 0 * * *'
  workflow_dispatch: # 手動実行も可能

jobs:
  generate-article:
    runs-on: ubuntu-latest
    
    # 修正点：リポジトリへの書き込み権限を追加
    permissions:
      contents: write
      
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # google-generativeaiライブラリを強制的に最新版にアップグレード
        pip install --upgrade google-generativeai
        # 他に必要なライブラリがあればここでインストール
        # pip install -r requirements.txt # ← もし他にもライブラリがあればこの行は残す
        
    - name: Generate article
      env:
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      run: python src/generate_article.py
      
    - name: Commit generated files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add generated_articles/
        git add src/used_themes.json
        # 変更があった場合のみコミットするように修正
        if ! git diff --staged --quiet; then
          git commit -m "Generate daily article $(date +'%Y-%m-%d')"
          git push
        else
          echo "No changes to commit."
        fi
